# Supervisor uses this to set BUILD_FROM when building the add-on.
# Without it, Supervisor defaults to ghcr.io/home-assistant/amd64-base:latest (no MynetworK app).
build_from:
  amd64: ghcr.io/erreur32/mynetwork:0.0.6
  aarch64: ghcr.io/erreur32/mynetwork:0.0.6
  armv7: ghcr.io/erreur32/mynetwork:0.0.6
